"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, Edit3, MessageSquarePlus, Search } from "lucide-react";
import { mockAnnouncements } from "@/data/mockAnnouncements";
import { AUDIENCES, type Announcement, type Audience, type FollowUp } from "@/lib/announcements";
import { CURRENT_ACADEMIC_YEAR } from "@/lib/academicYear";
import { DEPARTMENTS, departmentGroups, type Department } from "@/lib/departments";
import { addAnnouncementFollowUp, filterManagedAnnouncements, MANAGE_DEPARTMENT_KEY, updateAnnouncement, validateAnnouncementCore } from "@/lib/announcementManagement";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import styles from "./manage.module.css";

const nowIso=()=>new Date().toISOString();
const clone=(item:Announcement):Announcement=>structuredClone(item);
export default function ManagePage(){
 const [items,setItems]=useState(()=>mockAnnouncements.map(clone)); const [department,setDepartment]=useState<Department>("設備組"); const [query,setQuery]=useState(""); const [editing,setEditing]=useState<Announcement|null>(null); const [followTarget,setFollowTarget]=useState<Announcement|null>(null); const [followType,setFollowType]=useState<FollowUp["type"]>("supplement"); const [message,setMessage]=useState(""); const [notice,setNotice]=useState("");
 useEffect(()=>{const saved=localStorage.getItem(MANAGE_DEPARTMENT_KEY);if(DEPARTMENTS.includes(saved as Department))setDepartment(saved as Department)},[]);
 const changeDepartment=(value:Department)=>{setDepartment(value);localStorage.setItem(MANAGE_DEPARTMENT_KEY,value);setQuery("")};
 const visible=useMemo(()=>filterManagedAnnouncements(items.filter(i=>i.academicYear===CURRENT_ACADEMIC_YEAR),department,query),[items,department,query]);
 const saveEdit=()=>{if(!editing)return;const errors=validateAnnouncementCore(editing);if(Object.keys(errors).length){setNotice("請完成標題、適用對象與公告內容。");return}setItems(current=>updateAnnouncement(current,editing,nowIso()));setEditing(null);setNotice("已更新 Prototype 公告，原公告 ID 保持不變。");};
 const addFollow=()=>{if(!followTarget||!message.trim())return;setItems(current=>addAnnouncementFollowUp(current,followTarget.id,{createdAt:nowIso(),type:followType,message:message.trim()}));setFollowTarget(null);setMessage("");setNotice("已新增補充／稽催，歷史紀錄已保留。");};
 return <main className={styles.page}><header><div><Link href="/publish"><ArrowLeft/>返回發布頁</Link><p>{CURRENT_ACADEMIC_YEAR} 學年度 · 前端狀態 Prototype</p><h1>已發布公告管理</h1><span>找到既有公告、修正原內容，或新增補充／稽催。</span></div></header><div className={styles.shell}><section className={styles.controls}><label>目前發布單位<select value={department} onChange={e=>changeDepartment(e.target.value as Department)}>{departmentGroups.map(g=><optgroup key={g.office} label={g.office}>{g.departments.map(d=><option key={d}>{d}</option>)}</optgroup>)}</select></label><label className={styles.search}><Search/><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜尋公告標題或內容"/></label></section>{notice&&<p className={styles.notice}>{notice}</p>}<section className={styles.list} aria-label="公告列表">{visible.length===0?<p className={styles.empty}>目前沒有符合的公告。</p>:visible.map(item=><article key={item.id}><div className={styles.meta}><span>{new Date(item.publishedAt).toLocaleDateString("zh-TW")}</span>{item.updatedAt&&<span>最後更新 {new Date(item.updatedAt).toLocaleString("zh-TW")}</span>}</div><h2>{item.title}</h2><p>{item.audiences.join("、")}</p><div className={styles.flags}><span>{item.importantEvents.length?"有重要事項":"無重要事項"}</span><span>{item.deadlines.length?`有 ${item.deadlines.length} 筆截止期限`:"無截止期限"}</span><span>{item.followUps.length?`有 ${item.followUps.length} 筆補充／稽催`:"無補充／稽催"}</span></div><div className={styles.cardActions}><Button variant="outline" onClick={()=>setEditing(clone(item))}><Edit3/>編輯</Button><Button variant="outline" onClick={()=>setFollowTarget(item)}><MessageSquarePlus/>新增補充／稽催</Button></div></article>)}</section></div>
 <Dialog open={!!editing} onOpenChange={open=>!open&&setEditing(null)}><DialogContent className={styles.editor}>{editing&&<><DialogHeader><DialogDescription>編輯原公告 · ID {editing.id}</DialogDescription><DialogTitle>{editing.title}</DialogTitle></DialogHeader><label>公告標題<Input value={editing.title} onChange={e=>setEditing({...editing,title:e.target.value})}/></label><fieldset><legend>適用對象</legend><div className={styles.audiences}>{AUDIENCES.map(a=><label key={a}><Checkbox checked={editing.audiences.includes(a)} onCheckedChange={v=>setEditing({...editing,audiences:v?[...editing.audiences,a]:editing.audiences.filter(x=>x!==a)})}/>{a}</label>)}</div></fieldset><label>完整公告內容<Textarea value={editing.content} onChange={e=>setEditing({...editing,content:e.target.value})}/></label><EditorExtras item={editing} setItem={setEditing}/><div className={styles.editorActions}><Button variant="outline" onClick={()=>setEditing(null)}>取消</Button><Button onClick={saveEdit}>儲存 Prototype 修改</Button></div></>}</DialogContent></Dialog>
 <Dialog open={!!followTarget} onOpenChange={open=>!open&&setFollowTarget(null)}><DialogContent><DialogHeader><DialogDescription>{followTarget?.title}</DialogDescription><DialogTitle>新增補充／稽催</DialogTitle></DialogHeader><label className={styles.dialogField}>類型<select value={followType} onChange={e=>setFollowType(e.target.value as FollowUp["type"])}><option value="supplement">補充</option><option value="reminder">稽催</option></select></label><label className={styles.dialogField}>內容<Textarea value={message} onChange={e=>setMessage(e.target.value)} placeholder="輸入新增資訊；既有紀錄不會被覆蓋。"/></label><Button disabled={!message.trim()} onClick={addFollow}>加入歷史紀錄</Button></DialogContent></Dialog>
 </main>;
}

function EditorExtras({item,setItem}:{item:Announcement;setItem:(item:Announcement)=>void}){
 const updateEvent=(i:number,field:"date"|"time"|"title",value:string)=>setItem({...item,importantEvents:item.importantEvents.map((v,n)=>n===i?{...v,[field]:value}:v)});
 const updateDeadline=(i:number,field:"date"|"time"|"label",value:string)=>setItem({...item,deadlines:item.deadlines.map((v,n)=>n===i?{...v,[field]:value}:v)});
 return <div className={styles.extras}><section><h3>重要日期／活動</h3>{item.importantEvents.map((e,i)=><div className={styles.row} key={i}><Input type="date" value={e.date} onChange={x=>updateEvent(i,"date",x.target.value)}/><Input type="time" value={e.time||""} onChange={x=>updateEvent(i,"time",x.target.value)}/><Input value={e.title} onChange={x=>updateEvent(i,"title",x.target.value)}/></div>)}<Button variant="outline" size="sm" onClick={()=>setItem({...item,importantEvents:[...item.importantEvents,{date:"",title:""}]})}>＋ 補登重要事項</Button></section><section><h3>繳交／填報期限</h3>{item.deadlines.map((d,i)=><div className={styles.row} key={i}><Input type="date" value={d.date} onChange={e=>updateDeadline(i,"date",e.target.value)}/><Input type="time" value={d.time||""} onChange={e=>updateDeadline(i,"time",e.target.value)}/><Input value={d.label} onChange={e=>updateDeadline(i,"label",e.target.value)}/></div>)}<Button variant="outline" size="sm" onClick={()=>setItem({...item,deadlines:[...item.deadlines,{date:"",label:""}]})}>＋ 補登期限</Button></section><section><h3>相關網址</h3>{item.links.map((l,i)=><div className={styles.row} key={l.id}><Input value={l.label} onChange={e=>setItem({...item,links:item.links.map((v,n)=>n===i?{...v,label:e.target.value}:v)})}/><Input value={l.url} onChange={e=>setItem({...item,links:item.links.map((v,n)=>n===i?{...v,url:e.target.value}:v)})}/></div>)}<Button variant="outline" size="sm" onClick={()=>setItem({...item,links:[...item.links,{id:crypto.randomUUID(),label:"",url:"",type:"website",isPrimary:false}]})}>＋ 補登網址</Button></section><section><h3>公告圖片</h3><p>{item.attachments.length} 張圖片</p><Button variant="outline" size="sm" onClick={()=>setItem({...item,attachments:[...item.attachments,{id:crypto.randomUUID(),type:"image",name:"Prototype 圖片",caption:"",url:"https://placehold.co/800x500/png"}]})}>＋ 補登 Prototype 圖片</Button></section></div>
}
