"use client";
import { useEffect, useMemo, useState } from "react";
import { BellRing, CalendarDays, ChevronRight, Clock3, ImageIcon, Search, ZoomIn } from "lucide-react";
import { mockAnnouncements, DEMO_NOW } from "@/data/mockAnnouncements";
import { DEPARTMENTS, USER_IDENTITIES, type Announcement, type Attachment, type Audience, type UserIdentity } from "@/lib/announcements";
import { announcementsForIdentity, daysUntil, filterAnnouncements, needsAcademicYearConfirmation, readSavedIdentity, saveIdentity, type SavedIdentity, upcomingDeadlines, weeklyEvents } from "@/lib/announcementLogic";
import { announcementsForAcademicYear, CURRENT_ACADEMIC_YEAR, FRONTEND_ACADEMIC_YEARS } from "@/lib/academicYear";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

const weekday = ["日", "一", "二", "三", "四", "五", "六"];
const fmtDate = (value: string) => { const d = new Date(`${value.slice(0, 10)}T00:00:00`); return `${d.getMonth() + 1}/${d.getDate()}（${weekday[d.getDay()]}）`; };
const fmtPublished = (value: string) => new Intl.DateTimeFormat("zh-TW", { month: "numeric", day: "numeric", hour: "2-digit", minute: "2-digit" }).format(new Date(value));
const isToday = (value: string) => value === "2026-09-18";
const sortedFollowUps = (announcement: Announcement) => [...announcement.followUps].sort((a, b) => b.createdAt.localeCompare(a.createdAt));
const primaryLink = (announcement: Announcement) => announcement.links.find(link => link.isPrimary);
function AudienceTags({ values }: { values: readonly Audience[] }) { return <div className="tag-row">{values.map(value => <span className="tag" key={value}>{value}</span>)}</div>; }
function IdentityChoices({ onChoose }: { onChoose: (identity: SavedIdentity) => void }) { return <div className="identity-choices">{USER_IDENTITIES.map(identity => <button key={identity} onClick={() => onChoose(identity)}>{identity}<ChevronRight /></button>)}<button className="all-choice" onClick={() => onChoose("全部")}>查看全部公告</button></div>; }

export default function Home() {
  const [selected, setSelected] = useState<Announcement | null>(null);
  const [previewAttachment, setPreviewAttachment] = useState<Attachment | null>(null);
  const [identity, setIdentity] = useState<SavedIdentity | null | undefined>(undefined);
  const [newAcademicYear, setNewAcademicYear] = useState(false);
  const [viewMode, setViewMode] = useState<"related" | "all">("related");
  const [searchAcademicYear, setSearchAcademicYear] = useState<number>(CURRENT_ACADEMIC_YEAR);
  const [switchingIdentity, setSwitchingIdentity] = useState(false);
  const [query, setQuery] = useState("");
  const [department, setDepartment] = useState("全部");
  useEffect(() => { const stale = needsAcademicYearConfirmation(localStorage, CURRENT_ACADEMIC_YEAR); const saved = readSavedIdentity(localStorage, CURRENT_ACADEMIC_YEAR); setNewAcademicYear(stale); setIdentity(saved); setViewMode(saved === "全部" ? "all" : "related"); }, []);
  const chooseIdentity = (value: SavedIdentity) => { saveIdentity(localStorage, value, CURRENT_ACADEMIC_YEAR); setIdentity(value); setNewAcademicYear(false); setViewMode(value === "全部" ? "all" : "related"); setSwitchingIdentity(false); setQuery(""); };
  const currentYearAnnouncements = useMemo(() => announcementsForAcademicYear(mockAnnouncements, CURRENT_ACADEMIC_YEAR), []);
  const homepageAnnouncements = useMemo(() => viewMode === "all" || !identity || identity === "全部" ? currentYearAnnouncements : announcementsForIdentity(currentYearAnnouncements, identity as UserIdentity), [currentYearAnnouncements, identity, viewMode]);
  const searchYearAnnouncements = useMemo(() => announcementsForAcademicYear(mockAnnouncements, searchAcademicYear), [searchAcademicYear]);
  const scopedSearchAnnouncements = useMemo(() => viewMode === "all" || !identity || identity === "全部" ? searchYearAnnouncements : announcementsForIdentity(searchYearAnnouncements, identity as UserIdentity), [identity, searchYearAnnouncements, viewMode]);
  const events = useMemo(() => weeklyEvents(homepageAnnouncements, DEMO_NOW), [homepageAnnouncements]);
  const groupedEvents = useMemo(() => Object.groupBy(events, item => item.date), [events]);
  const deadlines = useMemo(() => upcomingDeadlines(homepageAnnouncements, DEMO_NOW), [homepageAnnouncements]);
  const results = useMemo(() => filterAnnouncements(scopedSearchAnnouncements, query, "全部", department), [scopedSearchAnnouncements, query, department]);

  if (identity === undefined) return <main className="identity-screen" aria-busy="true" />;
  if (identity === null) return <main className="identity-screen"><section className="identity-card"><div className="welcome-mark">義</div><p className="eyebrow-dark">{CURRENT_ACADEMIC_YEAR} 學年度 · 校內公務公告</p><h1>義學公務資訊站</h1><p className="welcome-copy">{newAcademicYear ? "新的學年度開始，請確認您本學年度的身分" : "快速找到與你相關的重要資訊"}</p><h2>請選擇您的身分</h2><IdentityChoices onChoose={chooseIdentity} /><p className="privacy-note">不需要登入，也不會要求姓名或帳號。</p></section></main>;
  return <main>
    <header className="site-header"><div className="header-inner"><div className="brand-mark" aria-hidden="true">義</div><div><p className="eyebrow">校內公務公告</p><h1>義學公務資訊站</h1></div><div className="date-stamp"><span>今天</span><strong>9/18 五</strong></div></div></header>
    <div className="identity-toolbar"><span>{CURRENT_ACADEMIC_YEAR} 學年度 · 目前身分：<strong>{identity === "全部" ? "查看全部" : identity}</strong></span><div><button onClick={() => setSwitchingIdentity(true)}>切換身分</button>{viewMode === "related" ? <button className="mode-button" onClick={() => { setViewMode("all"); setQuery(""); }}>查看全部公告</button> : identity !== "全部" && <button className="mode-button active" onClick={() => { setViewMode("related"); setQuery(""); }}>返回與我相關</button>}</div></div>
    <div className="page-shell">
      <section className="section section-primary" aria-labelledby="weekly-title"><div className="section-heading"><div><p className="section-kicker">WEEKLY FOCUS</p><h2 id="weekly-title">📌 本週重要事項</h2></div><span className="range">9/14 — 9/20</span></div><div className="event-board">
        {Object.entries(groupedEvents).map(([date, items]) => <div className={`event-day ${isToday(date) ? "today" : ""}`} key={date}><div className="day-label"><strong>{fmtDate(date)}</strong>{isToday(date) && <span>今天</span>}</div><div className="day-events">{items!.map(item => { const action = primaryLink(item.announcement); return <div className="event-row" key={`${item.announcement.id}-${item.date}-${item.time}-${item.title}`}><button className="event-main" onClick={() => setSelected(item.announcement)}><time>{item.time || "全天"}</time><span className="event-copy"><strong>{item.title}</strong><small>{item.announcement.department}｜{item.announcement.audiences.join("、")}</small></span><ChevronRight aria-hidden="true" /></button>{action && <a className="primary-action" href={action.url} target="_blank" rel="noopener noreferrer">開啟 {action.label}</a>}</div>})}</div></div>)}
      </div></section>
      <section className="section" aria-labelledby="deadline-title"><div className="section-heading"><div><p className="section-kicker">UPCOMING</p><h2 id="deadline-title">⏰ 即將截止</h2></div></div><div className="deadline-grid">{deadlines.map(({ announcement, deadline }) => { const days = daysUntil(deadline.date, DEMO_NOW); const action = primaryLink(announcement); return <article className={`deadline-card urgency-${days === 0 ? "today" : days <= 3 ? "soon" : "later"}`} key={`${announcement.id}-${deadline.date}-${deadline.time}-${deadline.label}`}><button className="deadline-main" onClick={() => setSelected(announcement)}><span className="deadline-status">{days === 0 ? "今天截止" : days <= 3 ? `${days} 天內截止` : `${deadline.date.slice(5).replace("-", "/")} 截止`}</span><strong>{deadline.label}</strong><span className="deadline-time"><Clock3 aria-hidden="true" />{deadline.time || "當日截止"}</span><small>{announcement.department}｜{announcement.audiences.join("、")}</small>{announcement.followUps.length > 0 && <span className="followup-badge">⚠ 有最新稽催</span>}</button>{action && <a className="primary-action" href={action.url} target="_blank" rel="noopener noreferrer">前往 {action.label}</a>}</article>})}</div></section>
      <section className="section" aria-labelledby="latest-title"><div className="section-heading"><div><p className="section-kicker">LATEST</p><h2 id="latest-title">📢 最新公告</h2></div><span className="count">{homepageAnnouncements.length} 則</span></div><div className="announcement-list">{homepageAnnouncements.slice(0, 4).map(a => <article className="announcement-card" key={a.id}><div className="announcement-meta"><span>{fmtPublished(a.publishedAt)}</span><span>{a.department}</span></div><h3>{a.title}</h3><AudienceTags values={a.audiences} />{a.followUps.length > 0 && <span className="followup-badge">⚠ 有最新稽催</span>}<button className="text-button" onClick={() => setSelected(a)}>查看完整公告 <ChevronRight aria-hidden="true" /></button></article>)}</div></section>
      <section className="section search-section" aria-labelledby="search-title"><div className="section-heading"><div><p className="section-kicker">ARCHIVE</p><h2 id="search-title">🔍 搜尋與篩選</h2></div><span className="scope-label">{viewMode === "all" ? "搜尋全部公告" : "搜尋與我相關"}</span></div><div className="year-switch" aria-label="學年度篩選">{FRONTEND_ACADEMIC_YEARS.map(year => <button key={year} className={searchAcademicYear === year ? "active" : ""} onClick={() => { setSearchAcademicYear(year); setQuery(""); }}>{year}學年度</button>)}</div><div className="filters"><label className="search-box"><span className="sr-only">搜尋公告</span><Search aria-hidden="true" /><Input value={query} onChange={e => setQuery(e.target.value)} placeholder="搜尋標題、內容或發布單位" /></label><div className="select-row single"><label><span>發布單位</span><Select value={department} onValueChange={setDepartment}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{["全部", ...DEPARTMENTS].map(v => <SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select></label></div></div><p className="result-count">{searchAcademicYear} 學年度 · 找到 {results.length} 則公告</p><div className="results-list">{results.map(a => <button key={a.id} className="result-row" onClick={() => setSelected(a)}><span><small>{a.academicYear} 學年度 · {fmtPublished(a.publishedAt)} · {a.department}</small><strong>{a.title}</strong><em>{a.audiences.join("、")}</em></span><ChevronRight aria-hidden="true" /></button>)}</div></section>
    </div><footer>義學國中 · 公務資訊查詢原型 <span aria-hidden="true">·</span> <a href="/admin">公務資訊發布</a></footer>
    <Dialog open={!!selected} onOpenChange={open => !open && setSelected(null)}><DialogContent className="detail-dialog">{selected && <><DialogHeader><DialogDescription>{selected.department} · {fmtPublished(selected.publishedAt)} 發布</DialogDescription><DialogTitle>{selected.title}</DialogTitle><AudienceTags values={selected.audiences} /></DialogHeader>{(selected.importantEvents.length > 0 || selected.deadlines.length > 0) && <div className="detail-dates">{selected.importantEvents.length > 0 && <div><h4><CalendarDays />重要日期／活動</h4>{selected.importantEvents.map((event, i) => <p key={i}><strong>{fmtDate(event.date)} {event.time}</strong><span>{event.title}</span></p>)}</div>}{selected.deadlines.length > 0 && <div className="deadline-detail"><h4><BellRing />繳交／填報期限</h4>{selected.deadlines.map((deadline, i) => <p key={i}><strong>{fmtDate(deadline.date)} {deadline.time}</strong><span>{deadline.label}</span></p>)}</div>}</div>}{selected.followUps.length > 0 && <section className="followup-panel"><h4>⚠ 最新稽催</h4><time>{fmtPublished(sortedFollowUps(selected)[0].createdAt)} 更新</time><p>{sortedFollowUps(selected)[0].message}</p>{selected.followUps.length > 1 && <details><summary>查看過往稽催</summary><div className="followup-history">{sortedFollowUps(selected).slice(1).map((item, i) => <article key={i}><time>{fmtPublished(item.createdAt)}</time><p>{item.message}</p></article>)}</div></details>}</section>}<div className="detail-content"><h4>公告內容</h4><p>{selected.content}</p></div>{selected.attachments.length > 0 && <section className="attachment-section"><h4><ImageIcon />公告圖片／附件</h4><div className="attachment-grid">{selected.attachments.map(attachment => <figure key={attachment.id}><button onClick={() => setPreviewAttachment(attachment)} aria-label={`放大查看 ${attachment.name}`}><img src={attachment.url} alt={attachment.caption || attachment.name} /><span><ZoomIn />放大查看</span></button><figcaption><strong>{attachment.name}</strong>{attachment.caption && <span>{attachment.caption}</span>}</figcaption></figure>)}</div></section>}{selected.links.length > 0 && <section className="links-section"><h4>🔗 相關連結</h4><div>{selected.links.map(link => <article key={link.id} className={link.isPrimary ? "primary" : ""}><strong>{link.label}</strong>{link.isPrimary && <span>主要連結</span>}<a href={link.url} target="_blank" rel="noopener noreferrer">開啟連結 ↗</a></article>)}</div></section>}</>}</DialogContent></Dialog>
    <Dialog open={!!previewAttachment} onOpenChange={open => !open && setPreviewAttachment(null)}><DialogContent className="image-dialog">{previewAttachment && <><DialogHeader><DialogTitle>{previewAttachment.name}</DialogTitle>{previewAttachment.caption && <DialogDescription>{previewAttachment.caption}</DialogDescription>}</DialogHeader><img src={previewAttachment.url} alt={previewAttachment.caption || previewAttachment.name} /></>}</DialogContent></Dialog>
    <Dialog open={switchingIdentity} onOpenChange={setSwitchingIdentity}><DialogContent className="identity-dialog"><DialogHeader><DialogTitle>切換身分</DialogTitle><DialogDescription>首頁會立即改為顯示與新身分相關的資訊。</DialogDescription></DialogHeader><IdentityChoices onChoose={chooseIdentity} /></DialogContent></Dialog>
  </main>;
}
